### ISSUE TITLE
Database Timeout

### ISSUE THREAD

**Issue by MeganWil** [computationalmystic/augur-group6#2]
The database request is taking too long to the point the page timeouts during the instance. We believe it's the way the data is being called on the frontend in the Ghtorrent database.

**Comment by gabe-heim** [comment]
This will be fixed by limiting our metrics to derive a score to 3 metrics for each sector (code development, issue resolution, and community growth). This will decrease the time each request takes and from what I can tell, limiting to 3 metrics does not cause a timeout.
